### ISSUE TITLE
Signature with Multiple To or CC

### ISSUE THREAD

**Issue by SSkeith** [markenwerk/java-utils-mail-dkim#12]
Seems there is a signing  problem of multiple TO or multiple CC

OK -> h=From:To:Cc:Message-ID:Subject:MIME-Version:Content-Type:Content-Transfer-Encoding;
Failed -> h=From:To:Cc:Cc:Cc:Message-ID:Subject:MIME-Version:Content-Type:Content-Transfer-Encoding;
Failed -> h=From:To:To:Cc:Message-ID:Subject:MIME-Version:Content-Type:Content-Transfer-Encoding;

**Comment by toKrause** [comment]
There shouldn't be duplicate `To` and `Cc` headers.  Adding multiple recipients like
```
mimeMessage.addRecipient(RecipientType.TO, new InternetAddress("test1@example.org"));
mimeMessage.addRecipient(RecipientType.TO, new InternetAddress("test2@example.org"));
```
will create a single `To` header with a comma separated list of recipients (i.e. `To: test1@example.org, test2@example.org`). That being said, forcing multiple occurrences of a header like
```
mimeMessage.addHeader("To", "test1@example.org");
mimeMessage.addHeader("To", "test2@example.org");
```
did indeed produce an invalid signature.

According to section 5.4.2 of the DKIM specification header values have to be added from the bottom up (i.e. the last occurrence of a header field has to be added first). Will be fixed in the next version.

I will fix the issue shortly. Sorry for the long delay.
