### ISSUE TITLE
Can't parse using MimeMessage

### ISSUE THREAD

**Issue by travisspencer** [markenwerk/java-utils-mail-dkim#27]
I have an SMTP test server that uses Greenmail. That gets messages sent from the client that signs it with DKIM using this library. However, when trying to parse and print the message in the test SMTP server, I continually get this message when the contents are accessed like this `mimeMessage.getContent()`:

```
javax.mail.MessagingException: Missing start boundary
	at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:682)
	at javax.mail.internet.MimeMessage.getContent(MimeMessage.java:1469)
```

The `Content-Type` header is this:

```
multipart/alternative; 
	boundary="----=_Part_24_1070372854.1588833686749"
```

If I remove the `\r\n\t` in the debugger, then it works the next time the message is read.

Is this a bug in DKIM or just something I'm doing wrong in the receiving end?

**Comment by toKrause** [comment]
Is this still an issue or has the problem been found and solved?

DKIM shouldn't do anything to the content. It just adds an additional `DKIM-Signature`-header. DKIM normalizes the content to create the signature. But this normalization is performed on the fly while processing the content to create the signature. The actual content of the mail is unchanged by DKIM.

That being said it's not impossible that the mentioned issue is caused by this DKIM library. Java/Jakarta Mail usually wants  to stream the content of en email without loading the entire content int memory first. This is important, if an email is rather large (with a lot of attachments for example). The DKIM library obviously needs the entire content to create the signature. It therefore loads the entire content into memory, calculates the signature, writes all headers including the newly calculated `DKIM-Signature`-header and then writes the previously cached content. It's possible the the offending character sequence `\r\n\t` is introduced during this process.

I'd need a more complete example to investigate the issue.

**Comment by travisspencer** [comment]
No longer an issue. Thanks though, @toKrause .
