### ISSUE TITLE
new DkimMessage(message, dkimSigner) doesn't work with Jakarta mail

### ISSUE THREAD

**Issue by pnykamp** [markenwerk/java-utils-mail-dkim#31]
DkimMessage expects a  javax.mail.internet.MimeMessage as the first argument, therefore it does not work with Jakarta mail (2.0.0).  When I tried with Jakarta mail this was the only line that complained. I know this is meant to be a Java mail library, but it would be good to support Jakarta mail. After looking at the code I'm guessing if all the imports were changed to jakarta.mail it might work with no other changes, but then it would only support Jakarta. I don't know if one version can support both Java mail and Jakarta mail easily. I'm happy to create a version that supports Jakarta and contribute it if that was helpful.

**Comment by bbottema** [comment]
Jakarta Mail is the successor to JavaMail, I don't think it should support both versions. I do think it should support Jakarta Mail, otherwise people are stuck with JavaMail just because of _java-utils-mail-dkim_. It's stopping me from moving [Simple Java Mail](http://www.simplejavamail.org/) to Jakarta Mail, for example.

**Comment by bbottema** [comment]
You could start with jakarta.mail:1.6.3, which is exactly the same as JavaMail, but from the new group (in fact it's regarded as [JavaMail's last and final release](https://github.com/eclipse-ee4j/mail/releases/tag/1.6.3)). Even the package names haven't changed there yet. Simple Java Mail is currently on 1.6.5 (because 2.0.0 requires Java 8) and the changes are minimal.

**Comment by toKrause** [comment]
Supporting both, JavaMail and Jakarta Mail, would require extensive changes, because the original author never anticipated that this library would be used with different mail implementations. It seems to be time to move on to Jakarta Mail and leave JavaMail behind.

A new version of this library should shortly be available in Maven Central. The version number will fittingly be 2.0.0, because the move to Jakarta Mail is a major change.

**Comment by pnykamp** [comment]
So glad to hear that, thank you!
